services:

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "6767:6767"
    environment:
      PORT: 6767
      NODE_PORT: 8000
      ALL_NODES: "A,B,C,D,E,F"
    networks:
      - mesh
    depends_on:
      - node_a
      - node_b
      - node_c
      - node_d
      - node_e
      - node_f

  node_a:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "A"
      NODE_PORT: 8000
    networks:
      - mesh

  node_b:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "B"
      NODE_PORT: 8000
    networks:
      - mesh

  node_c:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "C"
      NODE_PORT: 8000
    networks:
      - mesh

  node_d:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "D"
      NODE_PORT: 8000
    networks:
      - mesh

  node_e:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "E"
      NODE_PORT: 8000
    networks:
      - mesh

  node_f:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      NODE_ID: "F"
      NODE_PORT: 8000
    networks:
      - mesh

networks:
  mesh:
    driver: bridge